# frozen_string_literal: true

# An in-app notification generated by one of the Notifications evaluator services.
# Notifications are deduplicated within a 24-hour window per job+kind pair (enforced
# in BaseEvaluator). They are soft-read via read_at rather than deleted, and are
# optionally linked to a job (optional because the job may be deleted later).
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :job, optional: true

  enum :kind, {
    stage_stall:        0, # job has had no status change in more than 14 days
    deadline_reminder:  1, # application deadline is within the next 48 hours
    follow_up_due:      2, # scheduled follow-up date is today or overdue
    interview_reminder: 3  # an interview is scheduled within the next 24 hours
  }

  validates :body, presence: true
  validates :kind, presence: true

  scope :unread, -> { where(read_at: nil) }
  scope :recent, -> { order(created_at: :desc) }

  def mark_read!
    update!(read_at: Time.current)
  end

  def self.unread_count_for(user)
    where(user: user, read_at: nil).count
  end
end
