# Immutable activity log entry attached to a job. status_change entries are
# auto-generated by Job callbacks and cannot be edited after creation (enforced
# by the cannot_edit_status_change validator). All other types are user-created.
# metadata is a JSONB column; for status_change entries it stores { from:, to: }.
class TimelineEntry < ApplicationRecord
  belongs_to :job

  enum :entry_type, {
    note:          "note",          # free-text note added by the user
    contact:       "contact",       # recorded interaction with a person at the company
    interview:     "interview",     # interview scheduled or completed (manual note)
    assessment:    "assessment",    # take-home test, coding challenge, or skills task
    follow_up:     "follow_up",     # follow-up action or reminder noted by the user
    status_change: "status_change"  # auto-generated when job status changes; not editable
  }

  validates :entry_type, presence: true
  validates :description, presence: true, length: { maximum: 1000 }
  validates :occurred_at, presence: true

  validate :cannot_edit_status_change, on: :update

  private

  def cannot_edit_status_change
    if entry_type_was == "status_change" && (description_changed? || entry_type_changed?)
      errors.add(:base, "Cannot edit auto-generated status change entries")
    end
  end
end
